'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../../lib/supabase/client';

type Sermon={id:string;slug:string;title:string;sermon_date:string;passage:string;speaker:string;content:string;body?:string;video_link:string;published:boolean;created_by:string|null;created_at:string};
type SpecialEvent={id:string;event_name:string;event_type:string;event_date:string;start_time:string;end_time:string|null;location:string;description:string;photo_paths:string[];published:boolean;created_by:string|null;created_at:string};
type Education={id:string;title:string;category:string|null;description:string|null;resource_link:string|null;video_link:string|null;published:boolean;created_by:string|null;created_at:string;updated_at:string};
type Tab='sermon'|'event'|'education'|'victory';
type SelectedPhoto={id:string;file:File;previewUrl:string;name:string};

const emptySermon:Sermon={id:'',slug:'',title:'',sermon_date:'',passage:'',speaker:'',content:'',body:'',video_link:'',published:false,created_by:null,created_at:''};
const emptyEvent:SpecialEvent={id:'',event_name:'',event_type:'Special Service',event_date:'',start_time:'',end_time:null,location:'',description:'',photo_paths:[],published:false,created_by:null,created_at:''};
const emptyEducation:Education={id:'',title:'',category:'Bible College',description:'',resource_link:'',video_link:'',published:false,created_by:null,created_at:'',updated_at:''};
const eventOptions=['Revival','Homecoming','Special Service','Guest Speaker','Fellowship','Bible College Event','Victory Path','Youth Event','Community Outreach','Other'];

export default function DashboardClient(){
 const [userId,setUserId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [pending,setPending]=useState(false); const [message,setMessage]=useState<string|null>(null); const [tab,setTab]=useState<Tab>('sermon');
 const [sermons,setSermons]=useState<Sermon[]>([]); const [events,setEvents]=useState<SpecialEvent[]>([]); const [education,setEducation]=useState<Education[]>([]);
 const [sermon,setSermon]=useState<Sermon>(emptySermon); const [event,setEvent]=useState<SpecialEvent>(emptyEvent); const [edu,setEdu]=useState<Education>(emptyEducation); const [files,setFiles]=useState<SelectedPhoto[]>([]); const fileRef=useRef<HTMLInputElement|null>(null);

 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();setUserId(data.session?.user.id??null);await refresh();setLoading(false)})()},[]);
 async function refresh(){const [s,e,d]=await Promise.all([supabase.from('sermons').select('*').order('created_at',{ascending:false}),supabase.from('special_events').select('*').order('created_at',{ascending:false}),supabase.from('education').select('*').order('created_at',{ascending:false})]);if(!s.error)setSermons(s.data??[]);if(!e.error)setEvents(e.data??[]);if(!d.error)setEducation(d.data??[])}
 function slug(v:string){return v.toLowerCase().replace(/[^a-z0-9\s-]/g,'').trim().replace(/\s+/g,'-')||'sermon'}
 function resetEvent(){files.forEach(f=>URL.revokeObjectURL(f.previewUrl));setFiles([]);setEvent(emptyEvent)}
 function pickFiles(e:React.ChangeEvent<HTMLInputElement>){const list=Array.from(e.target.files??[]);setFiles(x=>[...x,...list.map(file=>({id:crypto.randomUUID(),file,previewUrl:URL.createObjectURL(file),name:file.name}))]);if(fileRef.current)fileRef.current.value=''}
 async function saveSermon(published:boolean){if(!userId||!sermon.title||!sermon.sermon_date)return setMessage('Sermon title and date are required.');setPending(true);const payload={slug:slug(sermon.title),title:sermon.title,sermon_date:sermon.sermon_date,passage:sermon.passage,speaker:sermon.speaker,content:sermon.content,video_link:sermon.video_link,published,created_by:sermon.created_by??userId,updated_at:new Date().toISOString()};const r=sermon.id?await supabase.from('sermons').update(payload).eq('id',sermon.id):await supabase.from('sermons').insert(payload);setMessage(r.error?r.error.message:'Sermon saved.');if(!r.error){setSermon(emptySermon);await refresh()}setPending(false)}
 async function saveEvent(published:boolean){if(!userId||!event.event_name||!event.event_date||!event.location)return setMessage('Event name, date and location are required.');setPending(true);try{const id=event.id||crypto.randomUUID();const paths=[...event.photo_paths];for(const f of files){const path=`events/${id}/${Date.now()}-${f.file.name.replaceAll(' ','_')}`;const r=await supabase.storage.from('special-event-photos').upload(path,f.file);if(r.error)throw r.error;paths.push(r.data.path)}const payload={event_name:event.event_name,event_type:event.event_type,event_date:event.event_date,start_time:event.start_time,end_time:event.end_time,location:event.location,description:event.description,photo_paths:paths,published,created_by:event.created_by??userId,updated_at:new Date().toISOString()};const r=event.id?await supabase.from('special_events').update(payload).eq('id',event.id):await supabase.from('special_events').insert({id,...payload});if(r.error)throw r.error;resetEvent();await refresh();setMessage('Event saved. Calendar and gallery update automatically when published.')}catch(err){setMessage((err as Error).message)}setPending(false)}
 async function saveEducation(published:boolean){if(!userId||!edu.title)return setMessage('A title is required.');setPending(true);const category=tab==='victory'?'Victory Path':edu.category;const payload={title:edu.title,category,description:edu.description,resource_link:edu.resource_link,video_link:edu.video_link,published,created_by:edu.created_by??userId,updated_at:new Date().toISOString()};const r=edu.id?await supabase.from('education').update(payload).eq('id',edu.id):await supabase.from('education').insert(payload);setMessage(r.error?r.error.message:(tab==='victory'?'Victory Path update saved.':'Education saved.'));if(!r.error){setEdu(emptyEducation);await refresh()}setPending(false)}
 async function remove(type:'sermon'|'event'|'education',id:string){const table=type==='sermon'?'sermons':type==='event'?'special_events':'education';await supabase.from(table).delete().eq('id',id);await refresh()}

 const cards=useMemo(()=>[...sermons.map(x=>({type:'sermon' as const,id:x.id,title:x.title,published:x.published,raw:x})),...events.map(x=>({type:'event' as const,id:x.id,title:x.event_name,published:x.published,raw:x})),...education.map(x=>({type:'education' as const,id:x.id,title:x.title,published:x.published,raw:x}))],[sermons,events,education]);
 const input='w-full rounded-2xl border border-purple-200 bg-white px-4 py-3 text-sm outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200';
 return <div className="mt-8"><div className="rounded-3xl border border-purple-100 bg-white p-6 shadow-lg">
  <p className="text-sm font-semibold uppercase tracking-[0.3em] text-purple-700">Pastor Content Manager</p><h2 className="mt-2 text-3xl font-serif font-bold">Manage the New Hope App</h2><p className="mt-2 text-slate-600">Sermons, calendar events, photo gallery, education and New Hope / Victory Path can all be maintained here.</p>
  <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{([['sermon','Sermons'],['event','Calendar + Photos'],['education','Education'],['victory','Victory Path']] as [Tab,string][]).map(([k,l])=><button key={k} onClick={()=>{setTab(k);if(k==='victory')setEdu({...emptyEducation,category:'Victory Path'});}} className={`rounded-2xl px-3 py-3 text-sm font-bold ${tab===k?'bg-purple-700 text-white':'bg-purple-50 text-purple-800'}`}>{l}</button>)}</div>
  {message&&<div className="mt-4 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}
  <div className="mt-6 rounded-3xl bg-purple-50 p-5">
   {tab==='sermon'&&<div className="space-y-4"><h3 className="text-xl font-bold">Sermon</h3><input className={input} placeholder="Sermon title" value={sermon.title} onChange={e=>setSermon({...sermon,title:e.target.value})}/><input type="date" className={input} value={sermon.sermon_date} onChange={e=>setSermon({...sermon,sermon_date:e.target.value})}/><input className={input} placeholder="Scripture / passage" value={sermon.passage} onChange={e=>setSermon({...sermon,passage:e.target.value})}/><input className={input} placeholder="Speaker" value={sermon.speaker} onChange={e=>setSermon({...sermon,speaker:e.target.value})}/><textarea className={input} rows={7} placeholder="Sermon text" value={sermon.content} onChange={e=>setSermon({...sermon,content:e.target.value})}/><input className={input} placeholder="Optional video link" value={sermon.video_link} onChange={e=>setSermon({...sermon,video_link:e.target.value})}/><Actions pending={pending} draft={()=>saveSermon(false)} publish={()=>saveSermon(true)}/></div>}
   {tab==='event'&&<div className="space-y-4"><h3 className="text-xl font-bold">Calendar Event + Photo Album</h3><p className="text-sm text-slate-600">Published events appear on the public calendar. Any pictures attached to the event also appear in the public Photo Gallery.</p><input className={input} placeholder="Event name" value={event.event_name} onChange={e=>setEvent({...event,event_name:e.target.value})}/><select className={input} value={event.event_type} onChange={e=>setEvent({...event,event_type:e.target.value})}>{eventOptions.map(x=><option key={x}>{x}</option>)}</select><div className="grid gap-3 sm:grid-cols-3"><input type="date" className={input} value={event.event_date} onChange={e=>setEvent({...event,event_date:e.target.value})}/><input type="time" className={input} value={event.start_time} onChange={e=>setEvent({...event,start_time:e.target.value})}/><input type="time" className={input} value={event.end_time??''} onChange={e=>setEvent({...event,end_time:e.target.value||null})}/></div><input className={input} placeholder="Location" value={event.location} onChange={e=>setEvent({...event,location:e.target.value})}/><textarea className={input} rows={5} placeholder="Event details" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/><div className="rounded-2xl border border-purple-200 bg-white p-4"><p className="font-bold">Pictures / Photo Gallery</p><p className="mb-3 text-sm text-slate-600">Choose one or several pictures from a phone or computer.</p><input ref={fileRef} type="file" accept="image/*" multiple onChange={pickFiles}/>{files.length>0&&<div className="mt-3 grid grid-cols-3 gap-2">{files.map(f=><img key={f.id} src={f.previewUrl} alt={f.name} className="aspect-square w-full rounded-xl object-cover"/>)}</div>}</div><Actions pending={pending} draft={()=>saveEvent(false)} publish={()=>saveEvent(true)}/></div>}
   {(tab==='education'||tab==='victory')&&<div className="space-y-4"><h3 className="text-xl font-bold">{tab==='victory'?'New Hope / Victory Path':'Education'}</h3>{tab==='victory'&&<p className="text-sm text-slate-600">Publish program news, mentoring updates, basketball information, registration links, donation information or videos. These appear on the Victory Path page.</p>}<input className={input} placeholder={tab==='victory'?'Update title':'Education title'} value={edu.title} onChange={e=>setEdu({...edu,title:e.target.value})}/>{tab==='education'&&<input className={input} placeholder="Category" value={edu.category??''} onChange={e=>setEdu({...edu,category:e.target.value})}/>}<textarea className={input} rows={7} placeholder="Description" value={edu.description??''} onChange={e=>setEdu({...edu,description:e.target.value})}/><input className={input} placeholder="Optional resource / registration link" value={edu.resource_link??''} onChange={e=>setEdu({...edu,resource_link:e.target.value})}/><input className={input} placeholder="Optional video link" value={edu.video_link??''} onChange={e=>setEdu({...edu,video_link:e.target.value})}/><Actions pending={pending} draft={()=>saveEducation(false)} publish={()=>saveEducation(true)}/></div>}
  </div>
  <div className="mt-6"><h3 className="text-lg font-bold">Existing Content</h3><div className="mt-3 space-y-2">{cards.map(c=><div key={`${c.type}-${c.id}`} className="flex items-center justify-between gap-3 rounded-2xl border border-purple-100 p-3"><div><p className="font-semibold">{c.title}</p><p className="text-xs uppercase text-slate-500">{c.type==='education'&&(c.raw as Education).category==='Victory Path'?'Victory Path':c.type} · {c.published?'Published':'Draft'}</p></div><div className="flex gap-2"><button className="rounded-xl bg-purple-50 px-3 py-2 text-xs font-bold text-purple-700" onClick={()=>{if(c.type==='sermon'){setTab('sermon');setSermon(c.raw as Sermon)}else if(c.type==='event'){setTab('event');setEvent(c.raw as SpecialEvent)}else{const x=c.raw as Education;setTab(x.category==='Victory Path'?'victory':'education');setEdu(x)}}}>Edit</button><button className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700" onClick={()=>remove(c.type,c.id)}>Delete</button></div></div>)}</div></div>
  {loading&&<p className="mt-4 text-sm text-slate-500">Loading content...</p>}
 </div></div>
}

function Actions({pending,draft,publish}:{pending:boolean;draft:()=>void;publish:()=>void}){return <div className="flex justify-end gap-3"><button disabled={pending} onClick={draft} className="rounded-2xl border border-purple-300 bg-white px-5 py-3 text-sm font-bold text-purple-700 disabled:opacity-50">Save Draft</button><button disabled={pending} onClick={publish} className="rounded-2xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Publish</button></div>}
